// <auto-generated />
using System;
using ExpenseTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenseTracker.API.Migrations
{
    [DbContext(typeof(ExpenseDbContext))]
    [Migration("20260106135103_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpenseTracker.Api.Models.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Date");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("364717f7-9539-4248-a5e2-12d870885ff8"),
                            Amount = 25.50m,
                            Category = "Food",
                            Date = new DateTime(2026, 1, 1, 13, 51, 2, 42, DateTimeKind.Utc).AddTicks(1697),
                            Description = "Lunch at cafe"
                        },
                        new
                        {
                            Id = new Guid("36b2cfc3-ba1d-4dd2-9950-74ee530e31d7"),
                            Amount = 50.00m,
                            Category = "Transport",
                            Date = new DateTime(2026, 1, 3, 13, 51, 2, 42, DateTimeKind.Utc).AddTicks(1714),
                            Description = "Gas for car"
                        },
                        new
                        {
                            Id = new Guid("bf0eaeb8-1147-400e-983b-fdbb6a14642f"),
                            Amount = 120.00m,
                            Category = "Bills",
                            Date = new DateTime(2026, 1, 5, 13, 51, 2, 42, DateTimeKind.Utc).AddTicks(1725),
                            Description = "Internet bill"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
